package com.trafficproject.dataobject;

public class CarDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private String carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.fromCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private String fromcrossid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.toCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private String tocrossid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.maxVelocity
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private Integer maxvelocity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.planTime
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private Integer plantime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carID
     *
     * @return the value of car.carID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carID
     *
     * @param carid the value for car.carID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.fromCrossID
     *
     * @return the value of car.fromCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public String getFromcrossid() {
        return fromcrossid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.fromCrossID
     *
     * @param fromcrossid the value for car.fromCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setFromcrossid(String fromcrossid) {
        this.fromcrossid = fromcrossid == null ? null : fromcrossid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.toCrossID
     *
     * @return the value of car.toCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public String getTocrossid() {
        return tocrossid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.toCrossID
     *
     * @param tocrossid the value for car.toCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setTocrossid(String tocrossid) {
        this.tocrossid = tocrossid == null ? null : tocrossid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.maxVelocity
     *
     * @return the value of car.maxVelocity
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public Integer getMaxvelocity() {
        return maxvelocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.maxVelocity
     *
     * @param maxvelocity the value for car.maxVelocity
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setMaxvelocity(Integer maxvelocity) {
        this.maxvelocity = maxvelocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.planTime
     *
     * @return the value of car.planTime
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public Integer getPlantime() {
        return plantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.planTime
     *
     * @param plantime the value for car.planTime
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setPlantime(Integer plantime) {
        this.plantime = plantime;
    }
}