package com.trafficproject.dataobject;

public class CrossDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cross_info.id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cross_info.cross_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    private String crossId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cross_info.up_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    private String upRoadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cross_info.right_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    private String rightRoadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cross_info.down_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    private String downRoadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cross_info.left_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    private String leftRoadId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cross_info.id
     *
     * @return the value of cross_info.id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cross_info.id
     *
     * @param id the value for cross_info.id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cross_info.cross_id
     *
     * @return the value of cross_info.cross_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public String getCrossId() {
        return crossId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cross_info.cross_id
     *
     * @param crossId the value for cross_info.cross_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public void setCrossId(String crossId) {
        this.crossId = crossId == null ? null : crossId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cross_info.up_road_id
     *
     * @return the value of cross_info.up_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public String getUpRoadId() {
        return upRoadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cross_info.up_road_id
     *
     * @param upRoadId the value for cross_info.up_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public void setUpRoadId(String upRoadId) {
        this.upRoadId = upRoadId == null ? null : upRoadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cross_info.right_road_id
     *
     * @return the value of cross_info.right_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public String getRightRoadId() {
        return rightRoadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cross_info.right_road_id
     *
     * @param rightRoadId the value for cross_info.right_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public void setRightRoadId(String rightRoadId) {
        this.rightRoadId = rightRoadId == null ? null : rightRoadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cross_info.down_road_id
     *
     * @return the value of cross_info.down_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public String getDownRoadId() {
        return downRoadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cross_info.down_road_id
     *
     * @param downRoadId the value for cross_info.down_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public void setDownRoadId(String downRoadId) {
        this.downRoadId = downRoadId == null ? null : downRoadId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cross_info.left_road_id
     *
     * @return the value of cross_info.left_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public String getLeftRoadId() {
        return leftRoadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cross_info.left_road_id
     *
     * @param leftRoadId the value for cross_info.left_road_id
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    public void setLeftRoadId(String leftRoadId) {
        this.leftRoadId = leftRoadId == null ? null : leftRoadId.trim();
    }
}