package com.trafficproject.dataobject;

public class RoadDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road.id
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road.roadID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private String roadid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road.roadlength
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private Integer roadlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road.maxRoadVelocity
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private Integer maxroadvelocity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road.lanesNum
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private Integer lanesnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road.fromCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private String fromcrossid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road.toCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private String tocrossid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column road.isDuplex
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    private Byte isduplex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road.id
     *
     * @return the value of road.id
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road.id
     *
     * @param id the value for road.id
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road.roadID
     *
     * @return the value of road.roadID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public String getRoadid() {
        return roadid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road.roadID
     *
     * @param roadid the value for road.roadID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setRoadid(String roadid) {
        this.roadid = roadid == null ? null : roadid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road.roadlength
     *
     * @return the value of road.roadlength
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public Integer getRoadlength() {
        return roadlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road.roadlength
     *
     * @param roadlength the value for road.roadlength
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setRoadlength(Integer roadlength) {
        this.roadlength = roadlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road.maxRoadVelocity
     *
     * @return the value of road.maxRoadVelocity
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public Integer getMaxroadvelocity() {
        return maxroadvelocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road.maxRoadVelocity
     *
     * @param maxroadvelocity the value for road.maxRoadVelocity
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setMaxroadvelocity(Integer maxroadvelocity) {
        this.maxroadvelocity = maxroadvelocity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road.lanesNum
     *
     * @return the value of road.lanesNum
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public Integer getLanesnum() {
        return lanesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road.lanesNum
     *
     * @param lanesnum the value for road.lanesNum
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setLanesnum(Integer lanesnum) {
        this.lanesnum = lanesnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road.fromCrossID
     *
     * @return the value of road.fromCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public String getFromcrossid() {
        return fromcrossid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road.fromCrossID
     *
     * @param fromcrossid the value for road.fromCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setFromcrossid(String fromcrossid) {
        this.fromcrossid = fromcrossid == null ? null : fromcrossid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road.toCrossID
     *
     * @return the value of road.toCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public String getTocrossid() {
        return tocrossid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road.toCrossID
     *
     * @param tocrossid the value for road.toCrossID
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setTocrossid(String tocrossid) {
        this.tocrossid = tocrossid == null ? null : tocrossid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column road.isDuplex
     *
     * @return the value of road.isDuplex
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public Byte getIsduplex() {
        return isduplex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column road.isDuplex
     *
     * @param isduplex the value for road.isDuplex
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    public void setIsduplex(Byte isduplex) {
        this.isduplex = isduplex;
    }
}