package com.trafficproject.dao;

import com.trafficproject.dataobject.CarDO;

import java.util.List;

public interface CarDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int insert(CarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int insertSelective(CarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    CarDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int updateByPrimaryKeySelective(CarDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table car
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int updateByPrimaryKey(CarDO record);

    CarDO selectByCarId(String carID);

    List<CarDO> listCar();
}