package com.trafficproject.dao;

import com.trafficproject.dataobject.CrossDO;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

import java.util.List;


public interface CrossDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cross_info
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cross_info
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    int insert(CrossDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cross_info
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    int insertSelective(CrossDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cross_info
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    CrossDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cross_info
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    int updateByPrimaryKeySelective(CrossDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cross_info
     *
     * @mbg.generated Wed May 15 21:42:12 CST 2019
     */
    int updateByPrimaryKey(CrossDO record);

    CrossDO selectByCrossId(String crossID);
    List<CrossDO> listCross();
}