package com.trafficproject.dao;

import com.trafficproject.dataobject.RoadDO;

import java.util.List;

public interface RoadDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table road
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table road
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int insert(RoadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table road
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int insertSelective(RoadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table road
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    RoadDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table road
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int updateByPrimaryKeySelective(RoadDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table road
     *
     * @mbg.generated Mon May 13 21:09:49 CST 2019
     */
    int updateByPrimaryKey(RoadDO record);

    RoadDO selectByRoadID(String roadID);

    List<RoadDO> listRoad();
}